all: bam_thing

bam_thing: bam_check_hack.cpp
	g++ -o bam_thing bam_check_hack.cpp  -I/nfs/goldstein/software/samtools/samtools-1.5/htslib-1.5/ -L/nfs/goldstein/software/samtools/samtools-1.5/htslib-1.5/ -lhts -lcurl -lbz2 
        
